### ISSUE TITLE
Bump kotlin version for Flutter 2.10 compatibility

### ISSUE THREAD

**Issue by ulrikap** [diefferson/http_certificate_pinning#23]
Hey!

When upgrading to Flutter 2.10, the android implementation of this dependency breaks due to Kotlin version incompatibility. 

In order to be compatible, this dependency needs to bump this 
`ext.kotlin_version = <new version>'` and this  `classpath com.android.tools.build:gradle:<new version>'.`

Would be greatly appreciated!

**Comment by diefferson** [comment]
Hi @ulrikap  updated.
