### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by abdulrojakdev** [diefferson/http_certificate_pinning#31]
how to handle it ?

![B1301797-F132-4E56-A19C-BF12B49B7CC9](https://user-images.githubusercontent.com/83383753/186846100-29835821-1899-42c5-91b6-12e985901a39.jpeg)

**Comment by VasyaSmolyar** [comment]
Have a same question

**Comment by diefferson** [comment]
Hi there! 
This exception return when the fingerprint is not valid,  how handle this exception depend that what behavior you want that your app should have.
