### ISSUE TITLE
Unexpected Connection Not Secure

### ISSUE THREAD

**Issue by MattMe99** [diefferson/http_certificate_pinning#37]
Hi, there's seems to be some devices that are affected by [this](https://github.com/diefferson/http_certificate_pinning/issues/31) type of Exception already referenced in a thread. Problem is that the devices affected don't seem to have any reason not to work but the behaviour is very consistent and users who experience it do so every time.

No correlation so far with device model or app version. But there's seem to be an overwhelming majority of Android devices.

Couldn't debug any further details but in a case the user just bought the phone (OnePlus Nord 2) but we have seen it occurring in more expensive models (Pixel 7), but it seems to be no correlation on that side either. 

The exception: `PlatformException(CONNECTION_NOT_SECURE, Connection is not secure, Fingerprint doesn't match, null)`

**Comment by diefferson** [comment]
Hello @MattMe99  this error is the scenario that the certificate not matches with the expected, and what this lib should validate.

You are sure that there not attempt to mock the certificate for these users?
Some  things to help us to identify the problem could be:
The users with problem are using WIFI or Mobile Network?  In case of wifi there aren't  proxies present on this networks?
Your server has a fixed http certificate? If you are using services as backend, like firebase, or google cloud services like App Engine the certificate could be different by region or updated with some frequency.
