### ISSUE TITLE
Verification of every request

### ISSUE THREAD

**Issue by PawlikMichal25** [diefferson/http_certificate_pinning#39]
I'm very puzzled by this behaviour: https://github.com/diefferson/http_certificate_pinning/blob/master/lib/src/dio/certificate_pinning_interceptor.dart#L28

the whole point of SSL pinning is to have verification of _every_ request, isn't it?

some references:
- Dio official example also validating on every request https://github.com/cfug/dio/blob/c3f6fd70936df225e0c628659bf28c4661adf2f1/example/lib/certificate_pinning.dart#L29
- https://stackoverflow.com/a/75131954

**Comment by diefferson** [comment]
Hi @PawlikMichal25, good point, this behavior was added by a contributor, I will analyze this code remove it or change this behavior to be optional and disabled as default.
