### ISSUE TITLE
Fingerprint doesn't match when user is not connected to the internet

### ISSUE THREAD

**Issue by abdallah-odeh** [diefferson/http_certificate_pinning#40]
Unexpected exception was thrown when the user is not connected to the internet,
normally, did would throw `HttpException` or `SocketException`
but in my case, user was not connected, 
dio threw `HttpException`
http_certificate_pinning threw `CONNECTION_NOT_SECURE`
  
![Screen Shot 2023-03-29 at 1 01 00 PM](https://user-images.githubusercontent.com/68509938/228500477-2a65c87d-2999-455f-a120-66e5e3dc76ab.png)

**Comment by Exzhnik** [comment]
Hi,  I've taken the initiative to fork the repository and made updates to the exception handling. Now, all exceptions, including `HttpException` and `SocketException`, should be correctly thrown and handled even when the user is not connected to the internet. The issue with `http_certificate_pinning` throwing `CONNECTION_NOT_SECURE` in this case has been addressed. 

You can find the updated code on my fork at https://github.com/Exzhnik/http_certificate_pinning. 

Please feel free to check it out and let me know if there are any further issues or concerns. Your insights are highly appreciated.

**Comment by diefferson** [comment]
Hi @Exzhnik  feel free to open a PR with your changes.

**Comment by lmanerich** [comment]
Any chance to approve the PR?

**Comment by diefferson** [comment]
I'm waiting for iOS implementation to merge this PR.

**Comment by lmanerich** [comment]
> I'm waiting for iOS implementation to merge this PR.

This error happens in Android only. iOS already have a specific exception

**Comment by diefferson** [comment]
Deployed on last version 2.1.2
