### ISSUE TITLE
Http package issue in new flutter sdk version

### ISSUE THREAD

**Issue by naninydhruva** [diefferson/http_certificate_pinning#48]
Hi team,
I am facing issue with this package in new flutter sdk released 3.13.0, I want to update the http package to 1.0.0 which my depenecies suggesting but this package is giving conflict with the version of http since it is using 0.13.5,
please release a new version of this package as per new sdk requirements.

thanks,
Srinikethan

**Comment by naninydhruva** [comment]
@diefferson @nivisi , the issue is that wo ever using this package cannot update to latest flutter sdk if they are using social login packages.. since this package is depened on the http 0.13.5 and those require the http >=1.0.0. can you please update you packages and make necessary changes according to the new dart version released.

I am hoping this changes can be done quickly.. 😃

**Comment by diefferson** [comment]
Hello @naninydhruva  new version 2.1.0 released with this update, thanks for to notice
