### ISSUE TITLE
api requests take much time after integrate this with http

### ISSUE THREAD

**Issue by manish9161** [diefferson/http_certificate_pinning#6]
We have implemented this with http.

**Comment by shaz-tech** [comment]
This issue is happening because the API request is going in the main/UI thread. I resolved this locally. If the admin wants then I can commit my changes.

**Comment by diefferson** [comment]
@shaz-tech For sure you can contribute to us

**Comment by shaz-tech** [comment]
@diefferson Could you please release a new build.

**Comment by diefferson** [comment]
Sorry for my late, new release available.
