### ISSUE TITLE
Hello, could you update?

### ISSUE THREAD

**Issue by apocalipse9** [diefferson/http_certificate_pinning#8]
Hi man, how are you?

Could you please update http version? Your package is using ^0.12.0+4, but others packages are using ^0.13.0, like GoogleFonts, cached_network and etc...

**Comment by diefferson** [comment]
Of course, I will update and notify you here.

**Comment by apocalipse9** [comment]
Thank you so much man :) 
Great job!!!

**Comment by diefferson** [comment]
Hello @apocalipse9, unfortunately, dio and http are dependencies off http_certificate_pinning and both depend of the same lib (http_parser), but the version of http_parser that is required to http 0.13 is incompatible with the last version of Dio. 

So we need wait dio updates to update the http version.

**Comment by diefferson** [comment]
@apocalipse9 Updated!

**Comment by apocalipse9** [comment]
> @apocalipse9 Updated!

Thank you so much :)
